# Generated by Django 3.2 on 2021-04-27 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
